import Head from "next/head";
import Link from "next/link";
import styles from '../../styles/Home.module.css'
import Logo from "./Logo/Logo";

export default function MainTemplate({children, keywords, headTitle}) {
  return (
    <>
      <Head>
        <title>Jeanhy {headTitle}</title>
        <meta keywords={"Uh Chto-to cruto poluchaetsy" + keywords} />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="slategrey" />

        <link rel="shortcut icon" href="./src/icon.svg" />
        <link rel="apple-touch-icon" href="./src/icon.svg" />
        <link rel="mask-icon" href="./src/icon.svg" />

        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <meta http-equiv="Content-Security-Policy" content="defoult-src 'self'" />
        <meta name="application-name" content=""/> */}

        <meta name="robots" content="index,follow" />
        <meta name="googlebot" content="index,follow" />
        {/* <meta name="google" content="nositelinkssearchbox"> */}
        <meta name="google" content="notranslate" />
        <meta name="pinterest" content="nopin" />

        {/* <meta rel="author" href="https://github.com/pin-cup" />
        <meta rel="me" href="https://github.com/pin-cup" />
        <meta rel="me" href="mailto:alexander.poz.ur@gmail.com" />
        <meta rel="me" href="sms:" > */}

        {/* <base href="https://pin-cup.github.io/Profile/" /> */}
      </Head>

      <header className="header-container">
        <Logo />
        <nav className="menu-nav">
          <ul className="menu-container">
            <li className="menu-item">
              <Link href="/">
                <a>
                  Main
                </a>
              </Link>
            </li>
            
            <li className="menu-item">
              <Link href="/jeanhy">
                <a>
                  Jeanhy
                </a>
              </Link>
            </li>
          </ul>
        </nav>
      </header>

      <main className="main-container">
        {children}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </>
  )
}