import Head from "next/head";

export default function Meta({title, keywords}) {
  return (
    <Head>
      <title>Jeanhy {title}</title>
      {/* <meta keywords={"" + keywords} /> */}
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
      {/* <meta name="theme-color" content="slategrey" /> */}

      {/* <link rel="shortcut icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/favicon.ico" />
      <link rel="mask-icon" href="/favicon.ico" /> */}

      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      {/* <meta http-equiv="Content-Security-Policy" content="defoult-src 'self'" />
      <meta name="application-name" content=""/> */}

      {/* <meta name="robots" content="index,follow" />
      <meta name="googlebot" content="index,follow" />
      <meta name="google" content="nositelinkssearchbox">
      <meta name="google" content="notranslate" />
      <meta name="pinterest" content="nopin" /> */}

      {/* <meta rel="author" href="https://github.com/pin-cup" />
      <meta rel="me" href="https://github.com/pin-cup" />
      <meta rel="me" href="mailto:alexander.poz.ur@gmail.com" />
      <meta rel="me" href="sms:" > */}

      {/* <base href="https://pin-cup.github.io/Profile/" /> */}
    </Head>
  );
}
